# Generated by Django 4.0.4 on 2022-05-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_MVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Familia',
        ),
    ]
